package com.bookfair.service;

import com.bookfair.features.reservation.Reservation;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.util.ByteArrayDataSource;
import lombok.RequiredArgsConstructor;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.Context;
import com.bookfair.security.JwtUtils;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Email service for sending reservation confirmations with QR codes.
 * @author Nihadiyan
 */
@Service
@RequiredArgsConstructor
public class EmailService {

    private final TemplateEngine templateEngine;
    private final JavaMailSender mailSender;
    private final QrService qrService;
    private final JwtUtils jwtUtils;

    @org.springframework.beans.factory.annotation.Value("${app.backend.url:http://localhost:8080}")
    private String backendUrl;

    public void sendConfirmation(String to, List<Reservation> reservations) {
       if (to == null || to.trim().isEmpty()) {
           throw new IllegalArgumentException("Email recipient cannot be null or empty");
       }

       try {
           Context context = new Context();
           context.setVariable("reservations", reservations);
           
           // Use the first reservation ID for the download link if available
           String downloadUrl = "";
           if (!reservations.isEmpty() && reservations.get(0).getUser() != null) {
               String token = jwtUtils.generateJwtTokenFromUsername(reservations.get(0).getUser().getUsername());
               downloadUrl = backendUrl + "/api/v1/vendor/reservations/" + reservations.get(0).getId() + "/qr/download?token=" + token;
           }
           context.setVariable("downloadUrl", downloadUrl);

           String html = templateEngine.process("res_confirmation_email_template.html", context);
           if (html == null) {
               throw new IllegalStateException("Email template processing returned null");
           }

           String qrData = reservations.stream()
                   .map(res -> res.getQrCode())
                   .collect(Collectors.joining(","));


           MimeMessage mimeMessage = mailSender.createMimeMessage();

           MimeMessageHelper mimeMessageHelper = new MimeMessageHelper(mimeMessage, true, "UTF-8");

           mimeMessageHelper.setTo(to);


           mimeMessageHelper.setSubject("Book Fair Reservation Confirmation");

           mimeMessageHelper.setText(html, true);

           byte[] qrBytes = qrService.generateQrCode(qrData);
           mimeMessageHelper.addInline("qrCode", new ByteArrayDataSource(qrBytes, "image/png"));

           mailSender.send(mimeMessage);
    }
    
    public void sendReminderEmail(Reservation reservation) {
        if (reservation.getUser() == null || reservation.getUser().getEmail() == null) return;
        
        try {
            Context context = new Context();
            context.setVariable("reservation", reservation);
            context.setVariable("user", reservation.getUser());
            context.setVariable("event", reservation.getEventStall().getEvent());
            
            String html = templateEngine.process("res_reminder_email_template.html", context);
            
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            
            helper.setTo(reservation.getUser().getEmail());
            helper.setSubject("Reminder: Upcoming Event - " + reservation.getEventStall().getEvent().getName());
            helper.setText(html, true);
            
            mailSender.send(message);
        } catch (Exception e) {
            throw new RuntimeException("Failed to send reminder email", e);
        }
    }

    /**
     * Simple helper used by smoke‑check endpoint to verify mail wiring.
     */
    public void sendTestEmail(String to) {
        if (to == null || to.trim().isEmpty()) {
            throw new IllegalArgumentException("Email recipient cannot be null or empty");
        }

        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, false, "UTF-8");
            helper.setTo(to);
            helper.setSubject("[BookFair] Test message");
            helper.setText("This is a test email generated by EmailService.", false);

            mailSender.send(message);
        } catch (Exception e) {
            throw new RuntimeException("Failed to send test email", e);
        }
    }

    /**
     * General-purpose plain text email sender; useful for quick manual checks.
     */
    public void sendSimpleEmail(String to, String subject, String body) {
        if (to == null || to.trim().isEmpty()) {
            throw new IllegalArgumentException("Email recipient cannot be null or empty");
        }
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, false, "UTF-8");
            helper.setTo(to);
            helper.setSubject(subject == null ? "" : subject);
            helper.setText(body == null ? "" : body, false);
            mailSender.send(message);
        } catch (Exception e) {
            throw new RuntimeException("Failed to send simple email", e);
        }
    }
}
