package com.bookfair.security;

import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

/**
 * Master security configuration — the blueprint Spring uses to build the entire
 * security filter chain at startup.
 *
 * This class defines:
 * - HOW users are authenticated (DaoAuthenticationProvider + BCrypt)
 * - WHERE the JWT filter runs (before Spring's default auth filter)
 * - WHICH endpoints are public vs protected
 *
 * All @Bean methods are called once at startup. Spring takes the returned objects
 * and wires them into the internal security machinery.
 */
@Configuration // this is a configuration class
@EnableWebSecurity // this is a security configuration class
@org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity // Enable @PreAuthorize
@RequiredArgsConstructor // tells spring this is a req arg constructor and auto generates a constructor lmao
public class SecurityConfig {


    // constructor injection auto generated by @RequiredArgsConstructor
    private final UserDetailsServiceImpl userDetailsService;
    private final JwtAuthenticationFilter jwtAuthenticationFilter;
    private final RateLimitingFilter rateLimitingFilter;


    /**
     * Configures the authentication provider that verifies login credentials.
     *
     * Plugs in two strategies:
     * - UserDetailsService: HOW to load a user from the database
     * - PasswordEncoder: HOW to hash and compare passwords (BCrypt)
     *
     * Spring calls this provider internally when authenticationManager.authenticate() is invoked.
     *
     * @return a configured DaoAuthenticationProvider
     */
    @Bean
    public DaoAuthenticationProvider authenticationProvider() {
        DaoAuthenticationProvider authProvider = new DaoAuthenticationProvider();
        // user details service has the login verification routine
        authProvider.setUserDetailsService(userDetailsService);
        authProvider.setPasswordEncoder(passwordEncoder());
        return authProvider;
    }

    /**
     * Exposes the AuthenticationManager as a bean so controllers can trigger login.
     *
     * Used in AuthController to programmatically authenticate a user:
     *   authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(username, password))
     *
     * @param authConfig Spring's auto-configured authentication setup
     * @return the authentication manager instance
     */
    // this triggers auth routine in the controller
    @Bean
    public AuthenticationManager authenticationManager(AuthenticationConfiguration authConfig) throws Exception {
        return authConfig.getAuthenticationManager();
    }

    /**
     * Defines the password hashing strategy for the entire application.
     *
     * BCrypt is a one-way hash function:
     * - Register: "mypassword" → "$2a$10$xK8f9jQ..." (stored in DB)
     * - Login: "mypassword" → hashed again → compared with DB hash
     *
     * @return a BCryptPasswordEncoder instance
     */
    // use BCrypt hash function for password encoding
    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    /**
     * Builds the security filter chain — the core of the entire security setup.
     *
     * Configures:
     * - CORS: disabled (same-origin via Nginx reverse proxy)
     * - CSRF: disabled (REST API uses JWT, not cookies)
     * - Sessions: stateless (every request must carry its own JWT)
     * - URL rules: which endpoints are public vs require authentication
     * - Filter order: JWT filter runs before Spring's default auth filter
     *
     * NOTE: Currently ALL endpoints are permitAll() for development.
     * TODO: Restrict endpoints once the Login Page is implemented.
     *
     * @param http the HttpSecurity builder provided by Spring
     * @return the built SecurityFilterChain
     */
    // this is the security filter chain .. remember everyone that this
    // will be after jwtauth tags a user with either a role or anonymous
    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http.cors(AbstractHttpConfigurer::disable)
            .csrf(AbstractHttpConfigurer::disable)
            .sessionManagement(session -> session.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
            .authorizeHttpRequests(auth -> 
                auth.requestMatchers("/api/email/**").permitAll()
                    .requestMatchers("/api/v1/auth/**").permitAll()
                    .requestMatchers("/api/v1/public/**").permitAll()
                    .requestMatchers("/uploads/**").permitAll()
                    .requestMatchers("/error").permitAll() // Allow Spring's internal error forwarding
                    
                    // System endpoints
                    .requestMatchers("/api/v1/system/**").hasRole("ADMIN")

                    // Admin only
                    .requestMatchers("/api/v1/admin/**").hasRole("ADMIN")
                    
                    // Employee/Admin only
                    .requestMatchers("/api/v1/employee/**").hasAnyRole("EMPLOYEE", "ADMIN")
                    
                    // Authenticated users (Vendors/Employees/Admins)
                    .requestMatchers("/api/v1/vendor/**").authenticated()
                    .requestMatchers("/api/v1/notifications", "/api/v1/notifications/**").authenticated()
                    .requestMatchers("/api/v1/payments/**").authenticated()
                    
                    .anyRequest().authenticated()
            );

        http.authenticationProvider(authenticationProvider());

        
        // just insert a pointer to the jwt authentication filter before the default authentication filter.. 
        // makes it so that the jwt authentication filter runs first .. you guys can think of it as a linked list insert 
        // it propegates up and down like a stack almost
        http.addFilterBefore(jwtAuthenticationFilter, UsernamePasswordAuthenticationFilter.class);
        http.addFilterBefore(rateLimitingFilter, JwtAuthenticationFilter.class);

        return http.build();
    }
}
