name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure VM
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            echo "Triggering deployment on VM..."
            az vm run-command invoke --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_VM_NAME }} --command-id RunShellScript --scripts "
              if [ ! -d ~/reservation_system ]; then
                cd ~ && git clone https://github.com/StereoSachiiii/reservation_system.git
              else
                cd ~/reservation_system && git pull
              fi
              
              chmod +x generate-ssl.sh
              ./generate-ssl.sh
              
              mkdir -p logs/backend logs/frontend
              
              if [ ! -f .env ]; then
                cp .env.production .env
              fi
              
              docker-compose -f docker-compose.yml up -d --build
              docker image prune -f
            "